config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, # ここの行にカンマを追加
    controllers: { registrations: 'registrations' }
  # get 'pages/home'
  root 'posts#index'
  get '/users/:id', to: 'users#show', as: 'user'
  resources :posts, only: %i(new create index show destroy) do
  # resources :groups, only: %i(new create edit update) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  # has_many :users, through: group_user
  # has_many :comments
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  # belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, optional:true
  belongs_to :post, optional:true
  
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  
  belongs_to :post, optional: true
  
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional:true
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # has_many :groups, dependent: :destroy #group機能
  # has_many :group_users
  
  accepts_nested_attributes_for :photos
  
  def liked_by(current_user)
    # user_idが一致するlikeを検索する
    Like.find_by(user_id: current_user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy  #dependent: :destroy オブジェクトが削除される時に関連づけられたオブジェクトのdestroyメソッドが実行(ユーザーに紐付く投稿削除)
  has_many :likes
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, length: { maximum: 50 }
  
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
   def index
   end
   
   def new
     @group = Group.new
     @group.users << current_user
   end
   
   def create
     @group = Group.new(group_params)
     if @group.save
       redirect_to root_path, notice: 'グループを作成しました'
       
     else
       render :new
     end
   end
   
   private
  def group_params
    params.require(:group).permit(:name, user_ids: [] )
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    end
  end
  
  def destroy
    @like = Like.find_by(id: params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    end
  end

  private
    def like_params
      params.permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i(show destroy)
  
  def new
    @post = Post.new
    @post.photos.build
  end
  
  def create
    @post = Post.new(post_params)
    if @post.photos.present?  #投稿の写真が存在するか確認
      @post.save
      # binding.pry
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end
  
  def index
    @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
  end
  
  def show
    @post = Post.find_by(id: params[:id])
  end
  
  def destroy
     @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find_by(id: params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    return user.profile_photo unless user.profile_photo.nil?
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Techpitgram</title>
    <%= csrf_meta_tags %>
    
    
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
       <%= render 'partial/navbar' if current_user %>

       <% if flash[:notice] %>
         <div class="alert alert-info">
           <%= flash[:notice] %>
         </div>
       <% end %>
       <% if flash[:alert] %>
         <div class="alert alert-danger">
           <%= flash[:alert] %>
         </div>
       <% end %>
       
       <div class="container">
         <%= yield %>
       </div>
       
       <%= render 'partial/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %> 
  <%= link_to "サインアウト", destroy_user_session_path, method: :delete %>
<% end %>
<p>このページは仮のトップページです。</p>
<%= link_to "仮のボタンです", "#", class: "btn btn-primary" %>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        Copyright © Techpit
      </p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-md-auto align-items-center">
            <li>
              <%= link_to "投稿", new_post_path, class: "btn btn-primary" %>
            </li>
            <li>
              <%= link_to "",  user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>